### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by davidxgames** [a-p-z/ESP32ArcadeBLEController#1]
I get an error in this line:

bleGamepad.setAutoReport(true);
----------------------------------------
exit status 1

'class BleGamepad' has no member named 'setAutoReport'; did you mean 'sendReport'?

**Comment by a-p-z** [comment]
Apparently, setAutoReport has been removed (https://github.com/lemmingDev/ESP32-BLE-Gamepad/commit/dd7d1b24b32dfc56925654a50ecdaf93da4d422c). There is a configuration class now.
Unfortunately, I have not updated this repository for a while. I will do it in few weeks. 
Thanks for the message

**Comment by davidxgames** [comment]
Thanks for answering, I'll wait hopefully and you can soon.

**Comment by a-p-z** [comment]
if you get error 'class NimBLEHIDDevice' has no member named 'batteryLevel', you need to download NimBLE Arduino from source and replace the one in your libraries folder as explained here: https://github.com/lemmingDev/ESP32-BLE-Gamepad/issues/120#issuecomment-1195977656
